name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print test
        run: echo "Hello world"
      - name: Print end
        run: echo "All done"
